---
title: JavaScript-functies schrijven
hero_image: images/banner.png
description: Hoe schrijf je functies in JS
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Functies schrijven en aanroepen
