title: Écrire des fonctions JavaScript
hero_image: images/banner.png
description: Comment écrire des fonctions en JS
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Écrire et appeler des fonctions
